version: '3.3'
services:
  mysql:
    networks:
        - group_network
    image: mysql:latest
    restart: always
    expose:
     - 3306
    environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
    volumes:
     - mysql_data:/var/lib/mysql
  wordpress:
    networks:
        - group_network
    image: wordpress
    restart: unless-stopped
    ports:
     - "127.0.0.1:8080:80"
    depends_on:
     - mysql
    environment:
     - "WORDPRESS_DB_NAME=$MYSQL_DATABASE"
     - "WORDPRESS_DB_USER=$MYSQL_USER"
     - "WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD"
     - VIRTUAL_HOST
     - LETSENCRYPT_HOST
     - LETSENCRYPT_EMAIL
    volumes:
     - wordpress_files:/var/www/html
     - ./containter_files:/var/
     - ./theme:/var/www/html/wp-content/themes
  backup:
    networks:
        - group_network
    image: aveltens/wordpress-backup
    restart: always
    volumes:
     - ./backups:/backups
     - wordpress_files:/var/www/html

    depends_on:
     - mysql
    environment:
     - "MYSQL_ENV_MYSQL_DATABASE=$MYSQL_DATABASE"
     - "MYSQL_ENV_MYSQL_USER=$MYSQL_USER"
     - "MYSQL_ENV_MYSQL_PASSWORD=$MYSQL_PASSWORD"
     - "MYSQL_PORT_3306_TCP_PORT=3306"

volumes:
  mysql_data:
  wordpress_files:
networks:
    group_network:

